# **NumPy**

## Introdução

O NumPy é uma biblioteca para tratamento de arrays multidimensionais, com diversas aplicações em cálculo numérico, álgebra linear, machine learning e diversas outras funções para programação científica. Sua implementação se baseia na linguagem C, o que proporciona alta performance no tratamento e manipulação de arrays, por meio de diversas funções e operadores.

In [3]:
import numpy as np

## ndarray

O objeto primordial quando trabalhamos com Numpy é o ndarray (classe). Ou seja, ao criar um array com esta biblioteca estamos instanciando objetos da classe ndarray, que herdam um conjunto de métodos e atributos que veremos neste notebook.

Podemos criar um objeto ndarray com a função np.array() (além de diversas outras que veremos mais adiante). Para tanto, passamos uma lista ou iterável contendo os respectivos elementos como argumento desta função. Vejamos este processo na linha de código abaixo.

In [4]:
b = np.array([1, 2, 3, 4, 5])

<table border="1"  align="justify">
<tr>
    <td><h4>Atributo</h4></td>
  <td><h4>Descrição</h4></td>
</tr>

<tr>
  <td>shape</td>
  <td>Tupla que contém o número de elementos para cada dimensão do array.</td>
</tr>
<tr>
  <td>size</td>
  <td>Número total de elementos de um array.</td>
</tr>
<tr>
  <td>ndim</td>
  <td>Número de dimensões.</td>
</tr>
<tr>
  <td>nbytes</td>
  <td>Número de bytes utilizado para armazenar os dados.</td>
</tr>
<tr>
  <td>dtype</td>
  <td>Tipo de dado dos elementos presentes em um array.</td>
</tr>
</table>


In [7]:
print(type(b))
print(b.dtype)

<class 'numpy.ndarray'>
int32


In [13]:
print("Array: ",b,"\n")
print("Dimensões: ",b.ndim)
print("Elementos por dimensão: ",b.shape)
print("Tamanho: ",b.size)

Array:  [1 2 3 4 5] 

Dimensões:  1
Elementos por dimensão:  (5,)
Tamanho:  5


In [15]:
k = np.array([[10.5, 1.3, 2], [4.3, 5.2, 1.8]])
print(k,"\n")
print('Shape: ', k.shape)
print('Número de dimensões: ', k.ndim)
print('Tamanho: ', k.size)
print('Dtype: ', k.dtype)

[[10.5  1.3  2. ]
 [ 4.3  5.2  1.8]] 

Shape:  (2, 3)
Número de dimensões:  2
Tamanho:  6
Dtype:  float64


## Tipos de dados

Podemos mudar o tipo de dado de um array passando o argumento dtype dentro da função np.array(). Checamos que array *a* possui elementos do tipo int. Vejamos como especificar explicitamente outro tipo de dado ao criar um array.

In [12]:
a = np.array([1,2,3], dtype=float)
a.dtype

dtype('float64')

Neste caso, nosso novo array *a* possui os mesmo números do exemplo anterior, não obstante seu tipo de dado seja float.
Por fim, o array *d* apresenta elementos do tipo *complex*.

In [15]:
d = np.array([[1,2,3],[4,5,6]], dtype=complex)
d

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

### astype

Após criarmos um ndarray podemos converter seu tipo de dados com a função astype:

In [17]:
z = np.array([1, 2, 3])
z.dtype

dtype('int32')

In [18]:
z = z.astype(str, copy=True)
z.dtype

dtype('<U11')

## Gerando arrays

In [5]:
array1 = np.array([[4,5,6],[7,8,9],[1,0,1]])
array1

array([[4, 5, 6],
       [7, 8, 9],
       [1, 0, 1]])

Além de listas, podemos passar tuplas como argumento da função np.array().

In [6]:
array2 = np.array(((4,5,6),(7,8,9),(1,0,1)))
array2

array([[4, 5, 6],
       [7, 8, 9],
       [1, 0, 1]])

#### np.zeros( )

A função np.zeros() permite criar um array contendo 0 em todas as suas entradas. Para tanto, passamos o *shape* do array como argumento da função.

In [23]:
zero = np.zeros(shape = (2,2))
zero

array([[0., 0.],
       [0., 0.]])

#### np.ones( )

A função np.ones() cria um array contendo 1 em todas as suas entradas. Sua implementação é similar a função anterior.

In [26]:
i = np.ones(shape = (2,2))
i

array([[1., 1.],
       [1., 1.]])

O tipo de dado default desta função é float.No entanto, podemos passar o argumento dtype dentro da função *np.ones()* para alterar para um outro tipo.

In [28]:
i.dtype

dtype('float64')

In [31]:
i = np.ones(shape = (2,2), dtype=int)
i.dtype

dtype('int64')

#### np.arange( )

Com a função *np.arange()* podemos criar uma sequência de números, construção similar a função built-in *range()* para números inteiros.

No exemplo abaixo criamos uma sequência de números inteiros. Mas, cabe observar que o primeiro o último número é $n-1$. Então, podemos pensar nesta função a partir da seguinte sintaxe: np.arange(start,end,step). O útlimo argumento (step) denota o espaçamento entre os valores. 

O exemplo abaixo cria uma sequência de números de 1 a 10 com espaçamento 2 (step).

In [38]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

Para inverter uma sequência de números dentro do np.arange() podemos passar -1 como step.

In [39]:
np.arange(2020,2009,-1)

array([2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010])

Podemos utilizar np.arange() com a função reshape para criar um array de duas dimensões,isto é, transformar um array de uma dimensão em uma matriz.

In [28]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### np.linspace( )

A função np.linspace() retorna um array com números com espaçamento uniforme em um intervalo definido.

Vamos criar um array com números dentro do intervalo [1,21] em 5 partes:

In [33]:
np.linspace(1,21,5)

array([ 1.,  6., 11., 16., 21.])

#### np.random( )

O NumPy possui diversas funções para gerar números aleatórios dentro do módulo np.random. Geraremos 10 números 
aleatórios entre 0 e 1 com a função random() deste módulo.

In [19]:
A = np.random.random(10)
A

array([0.39089466, 0.59692306, 0.04892582, 0.211422  , 0.84220304,
       0.6610878 , 0.18452301, 0.90848443, 0.12272799, 0.71773013])

#### np.full( )

Com a função np.full() podemos criar arrays que serão totalmente preenchidos com um determinado valor.

In [53]:
np.full(shape = (5,5),fill_value = 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

#### np.eye( )

Podemos criar também uma função identidade, com a função *np.eye()* ou ainda *np.identity()*. Passamos a ordem da matriz identidade como argumento.

In [21]:
print(np.eye(3), "\n")
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Operações com arrays

As operações aritméticas entre arrays (ou um mesmo array) sempre são feitas elemento a elemento.

In [30]:
a = np.array([10, 15, 20])
b = np.array([2, 5, 7])

In [25]:
print(a)
print(a+2)

[10 15 20]
[12 17 22]


In [26]:
print(b)
print(b-1)

[2 5 7]
[1 4 6]


In [31]:
print(a)
print(b, "\n")
print(a + b)

[10 15 20]
[2 5 7] 

[12 20 27]


Poderíamos ter utilizado as funções np.add(), np.subtract(), np.multiply() e np.divide() para obter os mesmos resultados anteriores.

#### np.add( )

In [70]:
np.add(a,b)

array([12, 20, 27])

#### np.subtract( )

In [71]:
np.subtract(a,b)

array([ 8, 10, 13])

#### np.multiply( )

In [72]:
np.multiply(a,b)

array([ 20,  75, 140])

#### np.divide( )

In [54]:
np.divide(a,b)

array([5.        , 3.        , 2.85714286])

#### np.power( )

In [33]:
c = np.array([4,16, 25])

In [34]:
np.power(c, 2)

array([ 16, 256, 625], dtype=int32)

#### np.sqrt( )

In [35]:
np.sqrt(c)

array([2., 4., 5.])

**Obs.:** As operações continuam sendo feitas elemento a elemento, mesmo em arrays multidimensionais. Assim, o operador * não efetua o produto matricial. Veremos mais adiante como utilizar esta biblioteca para calcular o produto entre matrizes.

## Comparação entre arrays

Os operadores >,>=,<=,==,!= efetuam comparação elemento a elemento entre arrays.

In [39]:
a = np.ones(5)
b = np.full(shape=5,fill_value=1)
c = np.arange(5)

print("a:", a)
print("b:", b)
print("c:", c)

a: [1. 1. 1. 1. 1.]
b: [1 1 1 1 1]
c: [0 1 2 3 4]


In [7]:
a == c  #verifica a igualdade entre os arrays elemento a elemento

array([False,  True, False, False, False])

In [9]:
a != c  #verifica a diferença elemento a elemento entre os arrays

array([ True, False,  True,  True,  True])

Para os demais operadores teremos a mesma validação (elemento a elemento):

In [11]:
c > a

array([False, False,  True,  True,  True])

## Incremento e decremento

Não há operadores específicos ++ ou -- para efetuar operações de incremento ou decremento. Para tal, podemos efetuar uma reatribuição de valores. Para incremento: array = array + escalar ou array += escalar. Para -, *, /, utilizamos sintaxe análoga.

In [43]:
ar = np.ones(10, dtype = int)
ar

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [44]:
ar += 5  #equivale a ar = ar + 5
print(ar)

[6 6 6 6 6 6 6 6 6 6]


## Manipulando o formato de um array

O NumPy possibilita modificar o shape de um array após sua criação.

#### array.reshape( )

Com a função reshape podemos fazer uma operação análoga a anterior, passando uma tupla com o novo shape do array.

In [51]:
a = np.arange(9)
print(a, "\n")

a = a.reshape((3,3))
print(a)

[0 1 2 3 4 5 6 7 8] 

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### array.ravel( )

Utilizaremos a função *ravel()* para efetuar a operação inversa a partir do array $a$, convertendo um array 2-D (duas dimensões) em 1-D.

In [52]:
print(a, "\n")
b = a.ravel()
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[0 1 2 3 4 5 6 7 8]


#### array.T

Outra manipulação possível é obter a transposta de um array. Tal operação não é válida para arrays 1-D.

In [53]:
print(a, "\n")
c = a.T
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[0 3 6]
 [1 4 7]
 [2 5 8]]


#### array.transpose( )

In [56]:
a = np.array([[3,1],[4,2],[4,5]])
print(a.shape)
a = a.transpose() 
print(a.shape)

(3, 2)
(2, 3)


## Indexação e fatiamento

Nesta seção aprenderemos a selecionar elemento por meio do índice (indexing) e fatiamento (slicing).

#### Indexação

A indexação do arrays NumPy é similar as listas do Python, em que cada elemento ocupa um determinado índice. No array o número 10 ocupa o índice 0, 15 possui índice 1 e assim sucessivamente. 

In [59]:
a = np.arange(10,30,5)
a

array([10, 15, 20, 25])

Então, para acessarmos um determinado elemento utilizamos *array[índice]*. Então, para acessar o número 10, que possui índice 0:

In [60]:
a[0]

10

Os arrays NumPy também suportam a indexação negativa, quando começamos a contar a partir do último elemento que possui índice -1 até o primeiro elemento do vetor. Em nosso exemplo, o número 25 possui índice -1, já o 20 índice -2, sucessivamente até o elemento 10 que possui índice -4.

In [59]:
a[-1]

25

Acessar múltiplos elementos por meio do índice:

In [61]:
a[[1,3]] # Acessa elementos 1 e 3

array([15, 25])

2-D arrays
* estrutura retangular de representação em linhas e colunas
* definido por dois eixos, onde 0 corresponde as linhas 1 as colunas
* a indexação é um par de valor (linha,coluna)
* array[linha,coluna]

In [62]:
matrix = np.arange(50,65).reshape(3,5)
matrix

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64]])

Para acessar o número 57:

In [63]:
matrix[1,2]

57

#### Fatiamento

Fatiamento significa extrair partes de um array ou gerar novos. Não especificar o valor do índice significa partir do valor mais extremo possível.

In [64]:
array = np.arange(30,50)
array

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

In [66]:
array[:10]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [154]:
array[5:15:2]

array([35, 37, 39, 41, 43])

In [156]:
array[:10:5]

array([30, 35])

#### Filtragem

In [69]:
print(array)
k = array[array > 40] # Retorna os valores que recebem "True" para a condição
print(k)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[41 42 43 44 45 46 47 48 49]


## Iteração dentro de arrays

Funciona de forma similar à iteração em listas.

In [71]:
z = np.array([1,2,3])
for numero in z: print(numero)

1
2
3


In [73]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
for linha in matrix: print(linha)

[1 2 3]
[4 5 6]
[7 8 9]


In [74]:
for linha in matrix: # Itera sobre cada lista
    for numero in linha: # Itera sobre cada elemento de cada lista
        print(numero) 

1
2
3
4
5
6
7
8
9


#### array.flat

Transforma um array em um objeto pelo qual podemos iterar sobre cada elemento, sem a necessidade de dois for's.

In [77]:
for numero in matrix.flat: print(numero)

1
2
3
4
5
6
7
8
9


## Aplicação de funções de forma vetorizada

In [78]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
np.apply_along_axis(func1d = np.mean, axis = 0, arr = matrix)

array([4., 5., 6.])

In [80]:
np.apply_along_axis(func1d = np.sum, axis = 0, arr = matrix)

array([12, 15, 18])

In [81]:
def exp(x):
    return x**2

np.apply_along_axis(func1d = exp, axis = 0, arr = matrix)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

## Estatísticas Descritivas (aggregate functions)

Opera em um conjunto de valores e gera como output um único resultado numérico.

In [82]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [89]:
print("Soma: ", a.sum())
print("Mínimo: ", a.min())
print("Máximo: ", a.max())
print("Média: ", a.mean())
print("Desvio-Padrão: ", a.std())

Soma:  6
Mínimo:  1
Máximo:  3
Média:  2.0
Desvio-Padrão:  0.816496580927726


In [90]:
array = np.array([7, 10, 9, 8, 11, 11, 12])

In [91]:
print('Soma: ', np.sum(array))
print('Valor mínimo: ', np.min(array))
print('Valor máximo: ', np.max(array))
print('Média: ', np.mean(array).round(2))
print('Mediana: ', np.median(array))
print('Desvio padrão: ', np.std(array).round(2))

Soma:  68
Valor mínimo:  7
Valor máximo:  12
Média:  9.71
Mediana:  10.0
Desvio padrão:  1.67


## Universal Functions (ufunc)

### np.sin( )

In [92]:
a = np.array([7, 10, 9, 8, 11, 11, 12])

In [93]:
np.sin(a)

array([ 0.6569866 , -0.54402111,  0.41211849,  0.98935825, -0.99999021,
       -0.99999021, -0.53657292])

In [94]:
np.log(a)

array([1.94591015, 2.30258509, 2.19722458, 2.07944154, 2.39789527,
       2.39789527, 2.48490665])

## Joining e splitting

In [98]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.full(shape = (2,4), fill_value = 5)

print(a, "\n")
print(b)

[[1 2 3 4]
 [5 6 7 8]] 

[[5 5 5 5]
 [5 5 5 5]]


#### np.row_stack( )

In [99]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [107]:
np.row_stack((a, b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

#### np.column_stack( )

In [100]:
np.hstack((a,b))

array([[1, 2, 3, 4, 5, 5, 5, 5],
       [5, 6, 7, 8, 5, 5, 5, 5]])

In [108]:
np.column_stack((a,b))

array([[1, 2, 3, 4, 5, 5, 5, 5],
       [5, 6, 7, 8, 5, 5, 5, 5]])

#### np.hsplit( )

Divide o array em partes iguais com base nas colunas

$C_{6 \times 10}$

In [111]:
C = np.arange(1,61).reshape(6,10)
print(C)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [114]:
[A,B] = np.hsplit(C,2)

In [116]:
print(A)

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]


In [117]:
print(B)

[[ 6  7  8  9 10]
 [16 17 18 19 20]
 [26 27 28 29 30]
 [36 37 38 39 40]
 [46 47 48 49 50]
 [56 57 58 59 60]]


#### np.vsplit( )

Divide o array em partes iguais com base nas linhas

In [120]:
[E,F] = np.vsplit(C,2)

In [121]:
print(E)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [122]:
print(F)

[[31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


## Operações Matriciais

In [123]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,1],[-1,2]])

#### np.dot( )

Realiza a multiplicação matricial

In [124]:
a.dot(b)

array([[ 3,  5],
       [11, 11]])

In [125]:
np.dot(a,b)

array([[ 3,  5],
       [11, 11]])